apiVersion: v1
kind: ConfigMap
metadata:
  name: quasar-backend-config
  namespace: quasar
  labels:
    app: quasar-backend
    tier: backend
data:
  NODE_ENV: "production"
  PORT: "4000"
  CORS_ORIGIN: "http://localhost:4173"
